export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  MONGODB_URI: 'MONGODB_URI',
  CORS_ORIGIN: 'CORS_ORIGIN',
  LOG_LEVEL: 'LOG_LEVEL',
  RATE_LIMIT_WINDOW_MS: 'RATE_LIMIT_WINDOW_MS',
  RATE_LIMIT_MAX: 'RATE_LIMIT_MAX',
  UPLOAD_RATE_LIMIT_MAX: 'UPLOAD_RATE_LIMIT_MAX',
  BODY_LIMIT: 'BODY_LIMIT',
  UPLOAD_MAX_RECORDS: 'UPLOAD_MAX_RECORDS',
} as const;
